### ISSUE TITLE
wstool update need to handle space in workspace directory path

### ISSUE THREAD

**Issue by misaleh** [vcstools/wstool#101] opened 2017-02-27 07:28 UTC
i was installing [Cartographer](https://google-cartographer-ros.readthedocs.io/en/latest/) and this error appeared 

when typing `wstool update -t src`

> [cartographer] Fetching https://github.com/googlecartographer/cartographer.git (version None) to /home/k3rnel-pan1k/test test/catkin_ws/src/cartographer
Too many arguments.

and when i changed my workspace directory to another without space in the name it worked fine, i think there is a problem in handling spacing in path name thats why it thinks that there is too many arguments.

**Comment by wjwwood** [comment] 2017-03-02 02:42
Thanks for the report. My guess is that loads of ROS related code doesn't handle whitespace in paths correctly :rofl:, due to the posix heritage. However, I'll have a look at it if I get time. (also pr's are always appreciated)

**Comment by rsinnet** [comment] 2017-03-02 05:31
The root cause of this is actually in vcstools in the way unsanitary paths are passed to the versioning tools. See vcstools/vcstools#122.

**Comment by dirk-thomas** [comment] 2020-06-25 15:29
Closing since the repository is about to be archived: see #154.

**Closed by dirk-thomas** 2020-06-25 15:29 UTC
Labels: bug
