### ISSUE TITLE
wstool update error: AF_UNIX path too long

### ISSUE THREAD

**Issue by realtime-neil** [vcstools/wstool#138] opened 2019-07-11 14:32 UTC
Here's something that happened:

```
$ wstool update --target-workspace /tmp/my-catkin-ws --delete-changed-uris --verbose
Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: AF_UNIX path too long
```

Something is attempting to create a unix domain socket with a too-long name, but I'm not sure if the problem is in `wstool` or a dependency thereof.

**Comment by tkruse** [comment] 2019-08-12 07:42
Is this something you can reproduce?

**Comment by realtime-neil** [comment] 2019-08-12 14:58
@tkruse , yes indeed:

```
#!/bin/sh

# repro-138

set -euvx

cleanup() {
    local status="$?"
    rm -rf "${TMPDIR}" || true
    return "${status}"
}

################################################################################

trap cleanup EXIT
export LC_ALL=C

export TMPDIR="/tmp/$(od -An -tx </dev/urandom | tr -cd '[:xdigit:]' | head -c74)"
mkdir -vp "${TMPDIR}"
printf "%s" "${TMPDIR}" | wc
(
    cd "$(mktemp -dt ros_catkin_ws.XXXXXX)"
    wstool init "${PWD}/src"
)
rm -rf "${TMPDIR}"

export TMPDIR="/tmp/$(od -An -tx </dev/urandom | tr -cd '[:xdigit:]' | head -c75)"
mkdir -vp "${TMPDIR}"
printf "%s" "${TMPDIR}" | wc
(
    cd "$(mktemp -dt ros_catkin_ws.XXXXXX)"
    wstool init "${PWD}/src"
)
rm -rf "${TMPDIR}"

exit "$?"
```

This reproducer suggests `wstool` does not tolerate a `TMPDIR` path exceeding 79 ascii characters.

**Comment by tkruse** [comment] 2019-10-27 02:13
So this seems to be affecting other python packages as well, e.g. https://github.com/broadinstitute/cromwell/issues/3647
I am not sure how this should best be fixed.

**Comment by realtime-neil** [comment] 2019-10-27 16:05
@tkruse if it's only `multiprocessing` that requires a `$TMPDIR`-resident fifo, then maybe don't do multiprocessing stuff when you can't create a fifo?

**Comment by tkruse** [comment] 2019-12-08 10:59
@realtime-neil : not sure if anyone would have the time to make the test, or whether any PR would ever be merged.

**Comment by realtime-neil** [comment] 2019-12-09 15:08
@tkruse I've waited a long time. As a former `wstool` user, I can wait indefinitely.

**Comment by dirk-thomas** [comment] 2020-06-25 15:28
Closing since the repository is about to be archived: see #154.

**Closed by dirk-thomas** 2020-06-25 15:28 UTC
