### ISSUE TITLE
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vcstools/wstool#125] opened 2018-09-23 12:52 UTC
I am installing ROS from source:
http://wiki.ros.org/melodic/Installation/Source
When I run 
`wstool init -j8 src melodic-desktop-full.rosinstall`
where ` melodic-desktop-full.rosinstall` is : 
```
- tar:
    local-name: actionlib
    uri: https://github.com/ros-gbp/actionlib-release/archive/release/melodic/actionlib/1.11.13-0.tar.gz
    version: actionlib-release-release-melodic-actionlib-1.11.13-0
- tar:
...

```

wstool is not able to download and extract the stuff, I get this error for example:

``
[rqt_publisher] Fetching https://github.com/ros-gbp/rqt_publisher-release/archive/release/melodic/rqt_publisher/0.4.8-0.tar.gz (version rqt_publisher-release-release-melodic-rqt_publisher-0.4.8-0) to /home/francesco/ros_catkin_ws/src/rqt_publisher
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
```
For each package. Any help?

Thank you in advance,

Francesco Saverio

**Comment by tkruse** [comment] 2018-09-24 00:47
Maybe a duplicate of
https://github.com/vcstools/vcstools/pull/140

Feel free to comment there, upvote, or otherwise get the attention of OSRF

**Comment by maziarz** [comment] 2019-01-13 18:11
I am having the same issue with `Melodic`, on `macOS 10.13.1` with Python 3.6.4.

**Comment by IsaiahvH** [comment] 2019-02-21 18:39
I am having the same issua with `Kinetic` on macOS 10.14.4 with `Python  2.7.10`.
How did you solve this; what do you mean by having installed @tkruse version?
I have successfully ran `pip install vcstools`, is there another/a newer version which prevents this tarball issue?

Kind regards!

**Comment by GiulioPettenuzzo** [comment] 2019-03-14 16:14
anyone has solved this issue??

**Comment by tkruse** [comment] 2019-03-14 22:54
Yes, see https://github.com/vcstools/vcstools/pull/140 as mentioned in the comments above.
The solution just needs releasing.

**Comment by llusserr** [comment] 2019-03-22 19:28
I had a similar issue and the solution recommended above did help unpack the tarballs which were downloaded.  But some tarballs could **not** be downloaded because the URL was incorrect for some reason.  

Anyway...

I removed the `--tar` flag when I ran  `rosinstall_generator`. 

For example, used:
`rosinstall_generator desktop_full --rosdistro melodic --deps > melodic-desktop-full.rosinstall`
instead of:
`rosinstall_generator desktop_full --rosdistro melodic --deps --tar > melodic-desktop-full.rosinstall`

If you simply want to install from source and don't care if you pull from the tarball then try this approach.

It allowed me to proceed past the 
`wstool init -j8 src melodic-desktop-full.rosinstall`
step without error.

**Comment by trungtin** [comment] 2019-03-26 10:02
For someone stumbles upon here from search.
The suggested solution is to install @tkruse patch directly
`pip install git+https://github.com/tkruse/vcstools@mock_server_tar_test`
(remember to uninstall 0.1.40 beforehand or else pip won't upgrade because same version number) or wait for 0.1.41 to be released

**Comment by AlexSunNik** [comment] 2019-04-24 21:47
> wstool init -j8 src melodic-desktop-full.rosinstall

This works! Thanks for your reply!

**Comment by mysablehats** [comment] 2019-04-29 09:01
> I had a similar issue and the solution recommended above did help unpack the tarballs which were downloaded. But some tarballs could **not** be downloaded because the URL was incorrect for some reason.
> 
> Anyway...
> 
> I removed the `--tar` flag when I ran `rosinstall_generator`.
> 
> For example, used:
> `rosinstall_generator desktop_full --rosdistro melodic --deps > melodic-desktop-full.rosinstall`
> instead of:
> `rosinstall_generator desktop_full --rosdistro melodic --deps --tar > melodic-desktop-full.rosinstall`
> 
> If you simply want to install from source and don't care if you pull from the tarball then try this approach.
> 
> It allowed me to proceed past the
> `wstool init -j8 src melodic-desktop-full.rosinstall`
> step without error.

this worked! ty

**Comment by dirk-thomas** [comment] 2020-06-25 15:28
Closing since the repository is about to be archived: see #154.

**Closed by dirk-thomas** 2020-06-25 15:28 UTC
