### ISSUE TITLE
Is it time to change the default filename from `.rosinstall` to `.wstool`?

### ISSUE THREAD

**Issue by jbohren** [vcstools/wstool#19] opened 2014-03-19 23:17 UTC
Would it be reasonable to change the default config file from `.rosinstall` to `.wstool`? The idea is that `wstool` will still recognize `.rosinstall` files, but will also process files named `.wstool`. By default going forward, `wstool init` would create a `.wstool` file.

**Comment by jbohren** [comment] 2015-02-04 20:54
So @dirk-thomas ... https://github.com/dirk-thomas/vcstool ?

**Comment by tkruse** [comment] 2015-02-04 21:12
vcstool is an alternative to rosinstall/wstool that does not support rosmake (no central file from which to produce a ROS_PACKAGE_PATH, or a setup.sh). It is viable in combination with catkin.

See https://groups.google.com/d/msg/ros-sig-buildsystem/VqziwxVnmb0/ui_BZ3qy4x4J for some history.

**Comment by dirk-thomas** [comment] 2015-02-04 21:25
The technical advantages of `vcstool` from my point of view:

* does not use any separate file for meta information, information about repositories can not go out-of-sync
* uses a different file format to "export" repository configurations (which does not allow collisions by design), can "import" the same file format (as well as rosinstall files)
* exports allow different "granularity": store specific branch / tag / hash in export file

The advantages from a user point of view:
* operates on any filesystem hierarchy
* has some advanced option like `vcs log --limit-untagged`
* allows running arbitrary commands on a set of repositories (see `vcs custom`)
* is a *very* thin wrapper around the native tools and does not perform any *magic* and therefore no surprises

There are certainly features in wstool / rosinstall which vcstool does not cover but for my personal use I never use those tools and therefore can't comment on them.

**Comment by jayvdb** [comment] 2017-11-23 01:34
Why not add support for `.wstool` as the default, and fall back to `.rosinstall`.

For extra sanity, if both exist, check they are identical, and fail if they are not.

**Comment by dirk-thomas** [comment] 2020-06-25 15:29
Closing since the repository is about to be archived: see #154.

**Closed by dirk-thomas** 2020-06-25 15:29 UTC
